on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - run: sudo apt-get install --no-install-recommends -y latexmk lmodern texlive-fonts-recommended
          - uses: actions/checkout@v2
          - run: make
